apiVersion: v1
kind: Service
metadata:
  name: log-cache-service
spec:
  ports:
  - port: 8080
    name: logcache
  - port: 8081
    name: logcache-gateway
  clusterIP: None
  selector:
    run: logcache
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    run: logcache
  name: logcache
spec:
  replicas: 1
  serviceName: "logcache"
  selector:
    matchLabels:
      run: logcache
  template:
    metadata:
      labels:
        run: logcache
    spec:
      initContainers:
      - name: init-logcache
        image: quay.io/alekssaul/kubectl:v1.10.2
        command: ["sh", "-c", "/root/init-log-cache.sh"]
      containers:
      - image: loggregator/log-cache
        imagePullPolicy: Always
        name: logcache
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tls
          readOnly: true
          mountPath: "/srv/certs"
      - image: loggregator/log-cache-gateway
        imagePullPolicy: Always
        name: logcache-gateway
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: tls
          readOnly: true
          mountPath: "/srv/certs"
      volumes:
      - name: tls
        secret:
          secretName: tls